# Generated by Django 4.0.2 on 2022-02-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('client', 'CLIENT')], default='client', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
