# Generated by Django 4.0.1 on 2022-02-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comuna',
        ),
    ]
